#                                                #
#                   CHAINTRAIN                   #
#                                                #
# Use %chainer as the name of the player who     #
# chained another and %chained for the name of   #
# the player who got chained.                    #
# You can use the normal mc colorcodes to use    #
# colors in the messages                         #
#                                                #

chainItem: '287'
chainCostsItem: true
chainCostsItemAmount: 1
disabledCommandsWhileChained:
- /tp
- /kill
chainedByMessage: &3You were chained by &4%chainer&3!
chainedMessage: &3You chained &4%chained&3!
moveWhileChainedMessage: &3You are unable to move while chained!
dropWhileChainedMessage: &3You are unable to drop items while chained!
interactWhileChainedMessage: &3You are unable to build while chained!
attackWhileChainedMessage: &3You are unable to attack while chained!
shootWhileChainedMessage: &3You are unable to shoot while chained!
unchainedChainedMessage: &4%chained &3have been unchained!
unchainedChainerMessage: &3You have been unchained!
disabledCommand: &3You are not allowed to use the Command &4%command &3while chained.
disabledCommands: &3You are not allowed to use the Command &4%command &3while chained.