name: Chaintrain
main: me.G4meM0ment.Chaintrain.Chaintrain
version: 1.0
softdepend: [Spout]
commands:
   chaintrain:
       description: Reloads the config.yml
       usage: /chaintrain help
   chain:
       description: Chains a player via command
       usage: /chaintrain help
   unchain:
       description: Unchains a chained player via command
       usage: /chaintrain help
   chainall:
       description: Chains all players online
       usage: /chaintrain help
   unchainall:
       description: Unchain all players online
       usage: /chaintrain help